opkg install ipset
opkg install ipt2socks 
opkg install iptables 
opkg install iptables-legacy 
opkg install iptables-mod-conntrack-extra 
opkg install iptables-mod-iprange 
opkg install iptables-mod-socket 
opkg install iptables-mod-tproxy 
opkg install kmod-ipt-nat 
opkg install dnsmasq-full
